### ISSUE TITLE
Poise::Error: Unable to find cookbook for file

### ISSUE THREAD

**Issue by davidsayers** [johnbellone/vault-cookbook#23]
When creating a wrapper cookbook I get the following error:
```
================================================================================
           Error executing action `restart` on resource 'vault_service[vault]'
           ================================================================================
           
           Poise::Error
           ------------
           poise_service[vault] (/tmp/kitchen/cache/cookbooks/wrapper-vault/recipes/server.rb line 17) had an error: Poise::Error: Unable to find cookbook for file "/tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb"
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/utils.rb:64:in `find_cookbook_name'
           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/defined_in.rb:69:in `poise_defined_in_cookbook'
           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/inversion.rb:237:in `default_inversion_attributes'
           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/inversion.rb:256:in `resolve_inversion_attribute'
           /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:30:in `resolve_inversion_provider'
       m/poise/helpers/inversion.rb:354:in `provides?'
           /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:125:in `block in action_restart'
           /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:154:in `call'
           /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:154:in `notify_if_service'
           /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:124:in `action_restart'
```

It works fine when not in a wrapper.

I managed to track the issue down to the following code:
```
vault_binary = File.join(service.install_path, 'vault', 'current', 'vault')
execute "setcap cap_ipc_lock=+ep #{vault_binary}" do
  not_if { node['platform_family'] == 'windows' }
  not_if { node['platform_family'] == 'mac_os_x' }
  not_if { config.disable_mlock }
  not_if "getcap #{vault_binary}|grep cap_ipc_lock+ep"
end
```

It doesn't feel like I am fixing the root cause but using the following resolved the issue:
```
vault_binary = File.join(service.install_path, 'vault', 'current', 'vault')
bash 'vault_mlock' do
  code "setcap cap_ipc_lock=+ep #{vault_binary}"
  not_if { node['platform_family'] == 'windows' }
  not_if { node['platform_family'] == 'mac_os_x' }
  not_if { config.disable_mlock }
  not_if "getcap #{vault_binary}|grep cap_ipc_lock+ep"
end
```

I am using the following settings:
Ubuntu 14.04
test-kitchen - 1.4.2

**Comment by johnbellone** [comment]
Would you be able to give ma little more information about the current version of the cookbook? This is working locally for me when I run `bin/kitchen converge default-ubuntu-1404` and then login to verify the process is running.

**Comment by davidsayers** [comment]
It only happens in a wrapper cookbook after running "kitchen destroy; kitchen setup". It doesn't happen if I run "kitchen converge" after the fail.

I have seen the error in version 1.3.1 & 1.4.0.

**Comment by davidsayers** [comment]
This might not be an issue with the vault cookbook.

It happens with chef-client 12.3.0 but not chef-client 12.4.3.

I have replicated it here if you are interested. If not, feel free to close.
https://github.com/davidsayers/vault-cluster-cookbook/commits/replicate-issue-23

**Comment by johnbellone** [comment]
Ah, I have a feeling it may be [chef/chef #3485](https://github.com/chef/chef/issues/3485).
