### ISSUE TITLE
No cluster address?

### ISSUE THREAD

**Issue by onetwopunch** [johnbellone/vault-cookbook#93]
There doesn't seem to be a cluster_address option for the listener. And as such when I try to set the node attribute, I get the following error:

```
     NoMethodError:
       undefined method `cluster_address' for VaultCookbook::Resource::VaultConfig
     # /var/folders/5y/2xp1l2t158g3_c33zyz6slvr0000gn/T/d20170131-13941-1dc3mak/cookbooks/hashicorp-vault/recipes/default.rb:23:in `block (2 levels) in from_file'
     # /var/folders/5y/2xp1l2t158g3_c33zyz6slvr0000gn/T/d20170131-13941-1dc3mak/cookbooks/hashicorp-vault/recipes/default.rb:23:in `each_pair'
     # /var/folders/5y/2xp1l2t158g3_c33zyz6slvr0000gn/T/d20170131-13941-1dc3mak/cookbooks/hashicorp-vault/recipes/default.rb:23:in `block in from_file'
     # /var/folders/5y/2xp1l2t158g3_c33zyz6slvr0000gn/T/d20170131-13941-1dc3mak/cookbooks/hashicorp-vault/recipes/default.rb:18:in `from_file'
```

I'm going ahead and adding it to my fork, but wanted the issue here to reference.

**Comment by onetwopunch** [comment]
Realized cluster address is in master just not the latest Supermarket release.
